/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatr_client;

import javax.swing.JOptionPane;
import javax.xml.ws.WebServiceException;

/**
 *
 * @author Minoj
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNewUser = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtLoginId = new javax.swing.JTextField();
        lblLoginId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnSignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login :: ChatR - Send and Receive Messages");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatr_client/chat-logo-256.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(186, 220, 88));

        lblNewUser.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lblNewUser.setForeground(new java.awt.Color(255, 255, 255));
        lblNewUser.setText("new user?");

        btnSignUp.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUp.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(186, 220, 88));
        btnSignUp.setText("Sign Up");
        btnSignUp.setToolTipText("Click to Open Sign Up.");
        btnSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignUp)
                    .addComponent(lblNewUser))
                .addGap(159, 159, 159))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSignUp, lblNewUser});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(lblNewUser)
                .addGap(18, 18, 18)
                .addComponent(btnSignUp)
                .addGap(29, 29, 29))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSignUp, lblNewUser});

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtLoginId.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtLoginId.setToolTipText("Alphabets and Numbers Only. Min 5 Chars. Max 15 Chars.");
        txtLoginId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 195, 199), 1, true));
        txtLoginId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLoginId.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtLoginId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginIdFocusLost(evt);
            }
        });

        lblLoginId.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblLoginId.setForeground(new java.awt.Color(106, 176, 76));
        lblLoginId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginId.setText("login id");

        lblPassword.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(106, 176, 76));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("password");

        txtPassword.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtPassword.setToolTipText("Min. 8 Characters Long: An Uppercase, Lowercase, Number and No whitespaces");
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 195, 199), 1, true));
        txtPassword.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        btnSignIn.setBackground(new java.awt.Color(186, 220, 88));
        btnSignIn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign In");
        btnSignIn.setToolTipText("Click to Sign In");
        btnSignIn.setBorder(null);
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoginId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblLoginId, lblPassword, txtLoginId, txtPassword});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblLoginId, lblPassword, txtLoginId, txtPassword});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        String login_id;
        String password;
        
        if(txtLoginId.getText().equals("") || txtPassword.getText().equals("")) {
            // If Fields are Empty
            JOptionPane.showMessageDialog(null, "Fields cannot be empty!","Login Error",JOptionPane.ERROR_MESSAGE);
            txtLoginId.setText("");
            txtPassword.setText("");
        } else if(txtLoginId.getText().length() < 5 || txtLoginId.getText().length() > 15) {
            JOptionPane.showMessageDialog(null, "Invalid Login ID length\nLength should be between 5 and 15.", "Login Error", JOptionPane.ERROR_MESSAGE);
            txtLoginId.setText("");
        } else if(!txtLoginId.getText().matches("[a-zA-Z0-9]*")) {
            JOptionPane.showMessageDialog(null, "Invalid Login ID\nShould only contain Letters and Numbers.", "Login Error", JOptionPane.ERROR_MESSAGE);
        } else {
            login_id = txtLoginId.getText();
            password = new String(txtPassword.getPassword());
            // Password should be atleast 8 Characters Long
            // Atleast One Uppercase Letter
            // Atleast One Lowercase Letter
            // Atleast One Number
            // No Whitespaces allowed
            if(!password.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,}$")) {
                JOptionPane.showMessageDialog(null, "Invalid Password\nAtleast 8 Characters Long\nOne Uppercase, Lowercase and Number\nNo Whitespaces allowed", "Invalid Password", JOptionPane.ERROR_MESSAGE);
            } else {
                
                try {
                    if(login(login_id, password)) {
                        // Log the User in
                        try {
                            ChatR_Client.setUser(getUsers(login_id));
                            ThreadsGUI gui = new ThreadsGUI();
                            this.dispose();
                            gui.setVisible(true);
                        } catch(WebServiceException e) {
                            System.out.println(e.getMessage());
                            JOptionPane.showMessageDialog(null, "Unable to Connect to Server.", "Server Down", JOptionPane.ERROR_MESSAGE);
                        }
                        
                    } else {
                        // Error Occured on the Server Side
                        JOptionPane.showMessageDialog(null, "Error occured on the server", "Server Error", JOptionPane.ERROR_MESSAGE);
                        txtLoginId.setText("");
                        txtPassword.setText("");
                    }
                } catch(LoginErrorException_Exception e) {
                    JOptionPane.showMessageDialog(null, "Invalid Login ID or Password", "Login Error", JOptionPane.ERROR_MESSAGE);
                } catch(WebServiceException e) {
                    JOptionPane.showMessageDialog(null, "Unable to Connect to Server.", "Server Down", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        RegisterGUI gui = new RegisterGUI();
        this.dispose();
        gui.setVisible(true);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtLoginIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginIdFocusGained
        txtLoginId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(186, 220, 88), 2, true));
    }//GEN-LAST:event_txtLoginIdFocusGained

    private void txtLoginIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginIdFocusLost
        txtLoginId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 195, 199), 1, true));
    }//GEN-LAST:event_txtLoginIdFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(186, 220, 88), 2, true));
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(189, 195, 199), 1, true));
    }//GEN-LAST:event_txtPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLoginId;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtLoginId;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    

    private static Users getUsers(java.lang.String loginId) {
        chatr_client.ChatR_Service service = new chatr_client.ChatR_Service();
        chatr_client.ChatR port = service.getChatRPort();
        return port.getUsers(loginId);
    }

    private static boolean login(java.lang.String loginId, java.lang.String password) throws LoginErrorException_Exception {
        chatr_client.ChatR_Service service = new chatr_client.ChatR_Service();
        chatr_client.ChatR port = service.getChatRPort();
        return port.login(loginId, password);
    }
    
}
